/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.1.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as init from "../init";
import type * as users from "../users";
import type * as utils_ability from "../utils/ability";
import type * as utils_auth from "../utils/auth";
import type * as utils_types from "../utils/types";
import type * as utils_zod from "../utils/zod";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  init: typeof init;
  users: typeof users;
  "utils/ability": typeof utils_ability;
  "utils/auth": typeof utils_auth;
  "utils/types": typeof utils_types;
  "utils/zod": typeof utils_zod;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
